// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using qlsv.Data;

#nullable disable

namespace web_qlsv.Migrations.QuanLySinhVienDb
{
    [DbContext(typeof(QuanLySinhVienDbContext))]
    [Migration("20241019090714_createAllDbContext")]
    partial class createAllDbContext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("qlsv.Models.Diem", b =>
                {
                    b.Property<string>("IdDiem")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasDefaultValueSql("(newid())");

                    b.Property<decimal?>("DiemKetThuc")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal?>("DiemQuaTrinh")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal?>("DiemTongKet")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("IdLopHocPhan")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("IdSinhVien")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.HasKey("IdDiem");

                    b.HasIndex("IdLopHocPhan");

                    b.HasIndex("IdSinhVien");

                    b.ToTable("Diem", (string)null);
                });

            modelBuilder.Entity("qlsv.Models.DiemDanh", b =>
                {
                    b.Property<string>("IdDiemDanh")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasDefaultValueSql("(newid())");

                    b.Property<bool?>("DaDiemDanh")
                        .HasColumnType("bit");

                    b.Property<string>("IdLopHocPhan")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("IdSinhVien")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("IdThoiGian")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.HasKey("IdDiemDanh");

                    b.HasIndex("IdLopHocPhan");

                    b.HasIndex("IdSinhVien");

                    b.HasIndex("IdThoiGian");

                    b.ToTable("DiemDanh", (string)null);
                });

            modelBuilder.Entity("qlsv.Models.GiaoVien", b =>
                {
                    b.Property<string>("IdGiaoVien")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("ChuyenMon")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TenGiaoVien")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdGiaoVien");

                    b.ToTable("GiaoVien", (string)null);
                });

            modelBuilder.Entity("qlsv.Models.LopHocPhan", b =>
                {
                    b.Property<string>("IdHocPhan")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("IdGiaoVien")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("TenHocPhan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdHocPhan");

                    b.HasIndex("IdGiaoVien");

                    b.ToTable("LopHocPhan", (string)null);
                });

            modelBuilder.Entity("qlsv.Models.SinhVien", b =>
                {
                    b.Property<string>("IdSinhVien")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("ChuyenNganh")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Lop")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("date");

                    b.HasKey("IdSinhVien");

                    b.ToTable("SinhVien", (string)null);
                });

            modelBuilder.Entity("qlsv.Models.SinhVienLopHocPhan", b =>
                {
                    b.Property<string>("IdSinhVienLopHocPhan")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("IdSinhVien_LopHocPhan")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("IdLopHocPhan")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("IdSinhVien")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.HasKey("IdSinhVienLopHocPhan");

                    b.HasIndex("IdLopHocPhan");

                    b.HasIndex("IdSinhVien");

                    b.ToTable("SinhVien_LopHocPhan", (string)null);
                });

            modelBuilder.Entity("qlsv.Models.ThoiGian", b =>
                {
                    b.Property<string>("IdThoiGian")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("Ngay")
                        .HasColumnType("date");

                    b.Property<TimeSpan>("ThoiGianBd")
                        .HasColumnType("time")
                        .HasColumnName("ThoiGianBD");

                    b.Property<TimeSpan>("ThoiGianKt")
                        .HasColumnType("time")
                        .HasColumnName("ThoiGianKT");

                    b.HasKey("IdThoiGian");

                    b.ToTable("ThoiGian", (string)null);
                });

            modelBuilder.Entity("qlsv.Models.ThoiGianLopHocPhan", b =>
                {
                    b.Property<string>("IdThoiGianLopHocPhan")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("IdThoiGian_LopHocPhan")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("IdLopHocPhan")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("IdThoiGian")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.HasKey("IdThoiGianLopHocPhan");

                    b.HasIndex("IdLopHocPhan");

                    b.HasIndex("IdThoiGian");

                    b.ToTable("ThoiGian_LopHocPhan", (string)null);
                });

            modelBuilder.Entity("qlsv.Models.Diem", b =>
                {
                    b.HasOne("qlsv.Models.LopHocPhan", "IdLopHocPhanNavigation")
                        .WithMany("Diems")
                        .HasForeignKey("IdLopHocPhan");

                    b.HasOne("qlsv.Models.SinhVien", "IdSinhVienNavigation")
                        .WithMany("Diems")
                        .HasForeignKey("IdSinhVien");

                    b.Navigation("IdLopHocPhanNavigation");

                    b.Navigation("IdSinhVienNavigation");
                });

            modelBuilder.Entity("qlsv.Models.DiemDanh", b =>
                {
                    b.HasOne("qlsv.Models.LopHocPhan", "IdLopHocPhanNavigation")
                        .WithMany("DiemDanhs")
                        .HasForeignKey("IdLopHocPhan");

                    b.HasOne("qlsv.Models.SinhVien", "IdSinhVienNavigation")
                        .WithMany("DiemDanhs")
                        .HasForeignKey("IdSinhVien");

                    b.HasOne("qlsv.Models.ThoiGian", "IdThoiGianNavigation")
                        .WithMany("DiemDanhs")
                        .HasForeignKey("IdThoiGian");

                    b.Navigation("IdLopHocPhanNavigation");

                    b.Navigation("IdSinhVienNavigation");

                    b.Navigation("IdThoiGianNavigation");
                });

            modelBuilder.Entity("qlsv.Models.LopHocPhan", b =>
                {
                    b.HasOne("qlsv.Models.GiaoVien", "IdGiaoVienNavigation")
                        .WithMany("LopHocPhans")
                        .HasForeignKey("IdGiaoVien");

                    b.Navigation("IdGiaoVienNavigation");
                });

            modelBuilder.Entity("qlsv.Models.SinhVienLopHocPhan", b =>
                {
                    b.HasOne("qlsv.Models.LopHocPhan", "IdLopHocPhanNavigation")
                        .WithMany("SinhVienLopHocPhans")
                        .HasForeignKey("IdLopHocPhan");

                    b.HasOne("qlsv.Models.SinhVien", "IdSinhVienNavigation")
                        .WithMany("SinhVienLopHocPhans")
                        .HasForeignKey("IdSinhVien");

                    b.Navigation("IdLopHocPhanNavigation");

                    b.Navigation("IdSinhVienNavigation");
                });

            modelBuilder.Entity("qlsv.Models.ThoiGianLopHocPhan", b =>
                {
                    b.HasOne("qlsv.Models.LopHocPhan", "IdLopHocPhanNavigation")
                        .WithMany("ThoiGianLopHocPhans")
                        .HasForeignKey("IdLopHocPhan");

                    b.HasOne("qlsv.Models.ThoiGian", "IdThoiGianNavigation")
                        .WithMany("ThoiGianLopHocPhans")
                        .HasForeignKey("IdThoiGian");

                    b.Navigation("IdLopHocPhanNavigation");

                    b.Navigation("IdThoiGianNavigation");
                });

            modelBuilder.Entity("qlsv.Models.GiaoVien", b =>
                {
                    b.Navigation("LopHocPhans");
                });

            modelBuilder.Entity("qlsv.Models.LopHocPhan", b =>
                {
                    b.Navigation("DiemDanhs");

                    b.Navigation("Diems");

                    b.Navigation("SinhVienLopHocPhans");

                    b.Navigation("ThoiGianLopHocPhans");
                });

            modelBuilder.Entity("qlsv.Models.SinhVien", b =>
                {
                    b.Navigation("DiemDanhs");

                    b.Navigation("Diems");

                    b.Navigation("SinhVienLopHocPhans");
                });

            modelBuilder.Entity("qlsv.Models.ThoiGian", b =>
                {
                    b.Navigation("DiemDanhs");

                    b.Navigation("ThoiGianLopHocPhans");
                });
#pragma warning restore 612, 618
        }
    }
}
