// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using qlsv.Data;

#nullable disable

namespace web_qlsv.Migrations.QuanLySinhVienDb
{
    [DbContext(typeof(QuanLySinhVienDbContext))]
    partial class QuanLySinhVienDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SinhVienLopHocPhan", b =>
                {
                    b.Property<string>("IdSinhVien")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("IdLopHocPhan")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.HasKey("IdSinhVien", "IdLopHocPhan")
                        .HasName("PK__SinhVien__531A1B36CDEDAB4C");

                    b.HasIndex("IdLopHocPhan");

                    b.ToTable("SinhVien_LopHocPhan", (string)null);
                });

            modelBuilder.Entity("ThoiGianLopHocPhan", b =>
                {
                    b.Property<string>("IdLopHocPhan")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("IdThoiGian")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.HasKey("IdLopHocPhan", "IdThoiGian")
                        .HasName("PK__ThoiGian__15C11AD9B63A9B11");

                    b.HasIndex("IdThoiGian");

                    b.ToTable("ThoiGian_LopHocPhan", (string)null);
                });

            modelBuilder.Entity("qlsv.Models.Diem", b =>
                {
                    b.Property<string>("IdLopHocPhan")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("IdSinhVien")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<decimal?>("DiemKetThuc")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal?>("DiemQuaTrinh")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal?>("DiemTongKet")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("IdLopHocPhan", "IdSinhVien")
                        .HasName("PK__Diem__72255A5ACAFEA388");

                    b.HasIndex("IdSinhVien");

                    b.ToTable("Diem", (string)null);
                });

            modelBuilder.Entity("qlsv.Models.DiemDanh", b =>
                {
                    b.Property<string>("IdSinhVien")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("IdThoiGian")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("IdLopHocPhan")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<bool?>("DaDiemDanh")
                        .HasColumnType("bit");

                    b.HasKey("IdSinhVien", "IdThoiGian", "IdLopHocPhan")
                        .HasName("PK__DiemDanh__817E0446A874C894");

                    b.HasIndex("IdLopHocPhan");

                    b.HasIndex("IdThoiGian");

                    b.ToTable("DiemDanh", (string)null);
                });

            modelBuilder.Entity("qlsv.Models.GiaoVien", b =>
                {
                    b.Property<string>("IdGiaoVien")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("ChuyenMon")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TenGiaoVien")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdGiaoVien")
                        .HasName("PK__GiaoVien__F4372AE328C6DBED");

                    b.ToTable("GiaoVien", (string)null);
                });

            modelBuilder.Entity("qlsv.Models.LopHocPhan", b =>
                {
                    b.Property<string>("IdHocPhan")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("IdGiaoVien")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("TenHocPhan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdHocPhan")
                        .HasName("PK__LopHocPh__6A35A4EC70344C38");

                    b.HasIndex("IdGiaoVien");

                    b.ToTable("LopHocPhan", (string)null);
                });

            modelBuilder.Entity("qlsv.Models.SinhVien", b =>
                {
                    b.Property<string>("IdSinhVien")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("ChuyenNganh")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Lop")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("date");

                    b.HasKey("IdSinhVien")
                        .HasName("PK__SinhVien__93ABE5766A04A8ED");

                    b.ToTable("SinhVien", (string)null);
                });

            modelBuilder.Entity("qlsv.Models.ThoiGian", b =>
                {
                    b.Property<string>("IdThoiGian")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("Ngay")
                        .HasColumnType("date");

                    b.Property<TimeSpan>("ThoiGianBd")
                        .HasColumnType("time")
                        .HasColumnName("ThoiGianBD");

                    b.Property<TimeSpan>("ThoiGianKt")
                        .HasColumnType("time")
                        .HasColumnName("ThoiGianKT");

                    b.HasKey("IdThoiGian")
                        .HasName("PK__ThoiGian__EDEFED40D5785B54");

                    b.ToTable("ThoiGian", (string)null);
                });

            modelBuilder.Entity("SinhVienLopHocPhan", b =>
                {
                    b.HasOne("qlsv.Models.LopHocPhan", null)
                        .WithMany()
                        .HasForeignKey("IdLopHocPhan")
                        .IsRequired()
                        .HasConstraintName("FK__SinhVien___IdLop__6383C8BA");

                    b.HasOne("qlsv.Models.SinhVien", null)
                        .WithMany()
                        .HasForeignKey("IdSinhVien")
                        .IsRequired()
                        .HasConstraintName("FK__SinhVien___IdSin__628FA481");
                });

            modelBuilder.Entity("ThoiGianLopHocPhan", b =>
                {
                    b.HasOne("qlsv.Models.LopHocPhan", null)
                        .WithMany()
                        .HasForeignKey("IdLopHocPhan")
                        .IsRequired()
                        .HasConstraintName("FK__ThoiGian___IdLop__5AEE82B9");

                    b.HasOne("qlsv.Models.ThoiGian", null)
                        .WithMany()
                        .HasForeignKey("IdThoiGian")
                        .IsRequired()
                        .HasConstraintName("FK__ThoiGian___IdTho__5BE2A6F2");
                });

            modelBuilder.Entity("qlsv.Models.Diem", b =>
                {
                    b.HasOne("qlsv.Models.LopHocPhan", "IdLopHocPhanNavigation")
                        .WithMany("Diems")
                        .HasForeignKey("IdLopHocPhan")
                        .IsRequired()
                        .HasConstraintName("FK__Diem__IdLopHocPh__5EBF139D");

                    b.HasOne("qlsv.Models.SinhVien", "IdSinhVienNavigation")
                        .WithMany("Diems")
                        .HasForeignKey("IdSinhVien")
                        .IsRequired()
                        .HasConstraintName("FK__Diem__IdSinhVien__5FB337D6");

                    b.Navigation("IdLopHocPhanNavigation");

                    b.Navigation("IdSinhVienNavigation");
                });

            modelBuilder.Entity("qlsv.Models.DiemDanh", b =>
                {
                    b.HasOne("qlsv.Models.LopHocPhan", "IdLopHocPhanNavigation")
                        .WithMany("DiemDanhs")
                        .HasForeignKey("IdLopHocPhan")
                        .IsRequired()
                        .HasConstraintName("FK__DiemDanh__IdLopH__5812160E");

                    b.HasOne("qlsv.Models.SinhVien", "IdSinhVienNavigation")
                        .WithMany("DiemDanhs")
                        .HasForeignKey("IdSinhVien")
                        .IsRequired()
                        .HasConstraintName("FK__DiemDanh__IdSinh__5629CD9C");

                    b.HasOne("qlsv.Models.ThoiGian", "IdThoiGianNavigation")
                        .WithMany("DiemDanhs")
                        .HasForeignKey("IdThoiGian")
                        .IsRequired()
                        .HasConstraintName("FK__DiemDanh__IdThoi__571DF1D5");

                    b.Navigation("IdLopHocPhanNavigation");

                    b.Navigation("IdSinhVienNavigation");

                    b.Navigation("IdThoiGianNavigation");
                });

            modelBuilder.Entity("qlsv.Models.LopHocPhan", b =>
                {
                    b.HasOne("qlsv.Models.GiaoVien", "IdGiaoVienNavigation")
                        .WithMany("LopHocPhans")
                        .HasForeignKey("IdGiaoVien")
                        .HasConstraintName("FK__LopHocPha__IdGia__4D94879B");

                    b.Navigation("IdGiaoVienNavigation");
                });

            modelBuilder.Entity("qlsv.Models.GiaoVien", b =>
                {
                    b.Navigation("LopHocPhans");
                });

            modelBuilder.Entity("qlsv.Models.LopHocPhan", b =>
                {
                    b.Navigation("DiemDanhs");

                    b.Navigation("Diems");
                });

            modelBuilder.Entity("qlsv.Models.SinhVien", b =>
                {
                    b.Navigation("DiemDanhs");

                    b.Navigation("Diems");
                });

            modelBuilder.Entity("qlsv.Models.ThoiGian", b =>
                {
                    b.Navigation("DiemDanhs");
                });
#pragma warning restore 612, 618
        }
    }
}
