version: '3.8'

services:
  # Sql Server
  sql_sv:
    image: mcr.microsoft.com/mssql/server
    container_name: sql_db_server
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'P@ss12345'
    ports:
      - '1435:1433' 
    restart: unless-stopped
    # user: '1000:1000'  # Uncomment only if required