INSERT INTO MonHoc (IdMonHoc, TenMonHoc, SoTinChi, SoTietHoc, IdKhoa) 
VALUES (NEWID(), N'Tin Đại Cương', 3, 45, (SELECT IdKhoa FROM Khoa WHERE TenKhoa = N'Công nghệ thông tin')),
    (NEWID(), N'Nhập môn CNTT', 3, 45, (SELECT IdKhoa FROM Khoa WHERE TenKhoa = N'Công nghệ thông tin')),
    (NEWID(), N'Toán rời rạc', 3, 45, (SELECT IdKhoa FROM Khoa WHERE TenKhoa = N'Công nghệ thông tin')),
    (NEWID(), N'Giải tích số', 3, 45, (SELECT IdKhoa FROM Khoa WHERE TenKhoa = N'Công nghệ thông tin')),
    (NEWID(), N'Kiến trúc máy tính', 3, 45, (SELECT IdKhoa FROM Khoa WHERE TenKhoa = N'Công nghệ thông tin')),
    (NEWID(), N'Mạng máy tính', 3, 45, (SELECT IdKhoa FROM Khoa WHERE TenKhoa = N'Công nghệ thông tin')),
    (NEWID(), N'Thiết kế web', 3, 45, (SELECT IdKhoa FROM Khoa WHERE TenKhoa = N'Công nghệ thông tin')),
    (NEWID(), N'Lập trình trực quan', 3, 45, (SELECT IdKhoa FROM Khoa WHERE TenKhoa = N'Công nghệ thông tin')),
    (NEWID(), N'Lập trình web', 3, 45, (SELECT IdKhoa FROM Khoa WHERE TenKhoa = N'Công nghệ thông tin')),
    (NEWID(), N'Học máy', 3, 45, (SELECT IdKhoa FROM Khoa WHERE TenKhoa = N'Công nghệ thông tin')),
    (NEWID(), N'Lập trình Android', 3, 45, (SELECT IdKhoa FROM Khoa WHERE TenKhoa = N'Công nghệ thông tin')),
    (NEWID(), N'Kỹ thuật lập trình', 3, 45, (SELECT IdKhoa FROM Khoa WHERE TenKhoa = N'Công nghệ thông tin')),
    (NEWID(), N'Giải tích 1', 3, 45, (SELECT IdKhoa FROM Khoa WHERE TenKhoa = N'Khoa học cơ bản')),
    (NEWID(), N'Đại số tuyến tính', 3, 45, (SELECT IdKhoa FROM Khoa WHERE TenKhoa = N'Khoa học cơ bản')),
    (NEWID(), N'Xác suất thống kê', 3, 45, (SELECT IdKhoa FROM Khoa WHERE TenKhoa = N'Khoa học cơ bản'));